sudo: required

services:
  - docker

language: cpp

compiler:
  - clang
  - gcc

notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always

before_install:
  - git submodule update --init
  - docker pull praqma/native-make:latest

script:
  - ls -al ${PWD}
  - docker run --rm --workdir=/workspace --volume ${PWD}:/workspace praqma/native-make:latest make all
  - docker run --rm --workdir=/workspace --volume ${PWD}:/workspace praqma/native-make:latest make test
